INSERT INTO dbo.sport (sport_code, sport_description) VALUES (1, 'Aeronautics');
INSERT INTO dbo.sport (sport_code, sport_description) VALUES (2, 'Alpine Skiing');
INSERT INTO dbo.sport (sport_code, sport_description) VALUES (3, 'Alpinism');
INSERT INTO dbo.sport (sport_code, sport_description) VALUES (4, 'Archery');
INSERT INTO dbo.sport (sport_code, sport_description) VALUES (5, 'Art Competitions');
INSERT INTO dbo.sport (sport_code, sport_description) VALUES (6, 'Athletics');
INSERT INTO dbo.sport (sport_code, sport_description) VALUES (7, 'Badminton');
INSERT INTO dbo.sport (sport_code, sport_description) VALUES (8, 'Baseball');
INSERT INTO dbo.sport (sport_code, sport_description) VALUES (9, 'Basketball');
INSERT INTO dbo.sport (sport_code, sport_description) VALUES (10, 'Basque Pelota');
INSERT INTO dbo.sport (sport_code, sport_description) VALUES (11, 'Beach Volleyball');
INSERT INTO dbo.sport (sport_code, sport_description) VALUES (12, 'Biathlon');
INSERT INTO dbo.sport (sport_code, sport_description) VALUES (13, 'Bobsleigh');
INSERT INTO dbo.sport (sport_code, sport_description) VALUES (14, 'Boxing');
INSERT INTO dbo.sport (sport_code, sport_description) VALUES (15, 'Canoeing');
INSERT INTO dbo.sport (sport_code, sport_description) VALUES (16, 'Cricket');
INSERT INTO dbo.sport (sport_code, sport_description) VALUES (17, 'Croquet');
INSERT INTO dbo.sport (sport_code, sport_description) VALUES (18, 'Cross Country Skiing');
INSERT INTO dbo.sport (sport_code, sport_description) VALUES (19, 'Curling');
INSERT INTO dbo.sport (sport_code, sport_description) VALUES (20, 'Cycling');
INSERT INTO dbo.sport (sport_code, sport_description) VALUES (21, 'Diving');
INSERT INTO dbo.sport (sport_code, sport_description) VALUES (22, 'Equestrianism');
INSERT INTO dbo.sport (sport_code, sport_description) VALUES (23, 'Fencing');
INSERT INTO dbo.sport (sport_code, sport_description) VALUES (24, 'Figure Skating');
INSERT INTO dbo.sport (sport_code, sport_description) VALUES (25, 'Football');
INSERT INTO dbo.sport (sport_code, sport_description) VALUES (26, 'Freestyle Skiing');
INSERT INTO dbo.sport (sport_code, sport_description) VALUES (27, 'Golf');
INSERT INTO dbo.sport (sport_code, sport_description) VALUES (28, 'Gymnastics');
INSERT INTO dbo.sport (sport_code, sport_description) VALUES (29, 'Handball');
INSERT INTO dbo.sport (sport_code, sport_description) VALUES (30, 'Hockey');
INSERT INTO dbo.sport (sport_code, sport_description) VALUES (31, 'Ice Hockey');
INSERT INTO dbo.sport (sport_code, sport_description) VALUES (32, 'Jeu De Paume');
INSERT INTO dbo.sport (sport_code, sport_description) VALUES (33, 'Judo');
INSERT INTO dbo.sport (sport_code, sport_description) VALUES (34, 'Lacrosse');
INSERT INTO dbo.sport (sport_code, sport_description) VALUES (35, 'Luge');
INSERT INTO dbo.sport (sport_code, sport_description) VALUES (36, 'Military Ski Patrol');
INSERT INTO dbo.sport (sport_code, sport_description) VALUES (37, 'Modern Pentathlon');
INSERT INTO dbo.sport (sport_code, sport_description) VALUES (38, 'Motorboating');
INSERT INTO dbo.sport (sport_code, sport_description) VALUES (39, 'Nordic Combined');
INSERT INTO dbo.sport (sport_code, sport_description) VALUES (40, 'Polo');
INSERT INTO dbo.sport (sport_code, sport_description) VALUES (41, 'Racquets');
INSERT INTO dbo.sport (sport_code, sport_description) VALUES (42, 'Rhythmic Gymnastics');
INSERT INTO dbo.sport (sport_code, sport_description) VALUES (43, 'Roque');
INSERT INTO dbo.sport (sport_code, sport_description) VALUES (44, 'Rowing');
INSERT INTO dbo.sport (sport_code, sport_description) VALUES (45, 'Rugby');
INSERT INTO dbo.sport (sport_code, sport_description) VALUES (46, 'Rugby Sevens');
INSERT INTO dbo.sport (sport_code, sport_description) VALUES (47, 'Sailing');
INSERT INTO dbo.sport (sport_code, sport_description) VALUES (48, 'Shooting');
INSERT INTO dbo.sport (sport_code, sport_description) VALUES (49, 'Short Track Speed Skating');
INSERT INTO dbo.sport (sport_code, sport_description) VALUES (50, 'Skeleton');
INSERT INTO dbo.sport (sport_code, sport_description) VALUES (51, 'Ski Jumping');
INSERT INTO dbo.sport (sport_code, sport_description) VALUES (52, 'Snowboarding');
INSERT INTO dbo.sport (sport_code, sport_description) VALUES (53, 'Softball');
INSERT INTO dbo.sport (sport_code, sport_description) VALUES (54, 'Speed Skating');
INSERT INTO dbo.sport (sport_code, sport_description) VALUES (55, 'Swimming');
INSERT INTO dbo.sport (sport_code, sport_description) VALUES (56, 'Synchronized Swimming');
INSERT INTO dbo.sport (sport_code, sport_description) VALUES (57, 'Table Tennis');
INSERT INTO dbo.sport (sport_code, sport_description) VALUES (58, 'Taekwondo');
INSERT INTO dbo.sport (sport_code, sport_description) VALUES (59, 'Tennis');
INSERT INTO dbo.sport (sport_code, sport_description) VALUES (60, 'Trampolining');
INSERT INTO dbo.sport (sport_code, sport_description) VALUES (61, 'Triathlon');
INSERT INTO dbo.sport (sport_code, sport_description) VALUES (62, 'Tug-Of-War');
INSERT INTO dbo.sport (sport_code, sport_description) VALUES (63, 'Volleyball');
INSERT INTO dbo.sport (sport_code, sport_description) VALUES (64, 'Water Polo');
INSERT INTO dbo.sport (sport_code, sport_description) VALUES (65, 'Weightlifting');
INSERT INTO dbo.sport (sport_code, sport_description) VALUES (66, 'Wrestling');
