INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (1, 'Art Competitions Mixed Architecture, Architectural Designs', 5);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (2, 'Archery Men''s Target Archery, 33 metres, Individual', 4);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (3, 'Wrestling Men''s Welterweight, Greco-Roman', 66);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (4, 'Wrestling Men''s All-Around, Greco-Roman', 66);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (5, 'Judo Men''s Middleweight', 33);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (6, 'Boxing Men''s Welterweight', 14);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (7, 'Weightlifting Men''s Middleweight', 65);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (8, 'Football Women''s Football', 25);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (9, 'Speed Skating Men''s 10,000 metres', 54);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (10, 'Art Competitions Mixed Literature, Epic Works', 5);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (11, 'Archery Men''s Unknown Event', 4);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (12, 'Swimming Men''s 200 metres Butterfly', 55);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (13, 'Cycling Women''s Keirin', 20);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (14, 'Cross Country Skiing Men''s 4 x 10 kilometres Relay', 18);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (15, 'Swimming Women''s 300 metres Freestyle', 55);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (16, 'Cycling Men''s Road Race, Team', 20);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (17, 'Athletics Women''s Discus Throw', 6);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (18, 'Cycling Men''s 2 mile', 20);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (19, 'Sailing Mixed 0-0.5 Ton', 47);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (20, 'Shooting Men''s Trap, Double Shot, 14 metres', 48);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (21, 'Cross Country Skiing Women''s 15 km Skiathlon', 18);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (22, 'Rowing Women''s Coxless Pairs', 44);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (23, 'Motorboating Mixed C-Class', 38);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (24, 'Cross Country Skiing Women''s 10 kilometres', 18);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (25, 'Weightlifting Women''s Middleweight', 65);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (26, 'Judo Women''s Extra-Lightweight', 33);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (27, 'Sailing Mixed One Person Dinghy', 47);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (28, 'Athletics Women''s 10 kilometres Walk', 6);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (29, 'Athletics Men''s 20 kilometres Walk', 6);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (30, 'Gymnastics Women''s Team All-Around', 28);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (31, 'Swimming Men''s 1,500 metres Freestyle', 55);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (32, 'Swimming Men''s 1,000 metres Freestyle', 55);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (33, 'Diving Men''s Plain High', 21);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (34, 'Freestyle Skiing Men''s Aerials', 26);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (35, 'Modern Pentathlon Women''s Individual', 37);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (36, 'Shooting Men''s Unknown Event', 48);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (37, 'Snowboarding Women''s Parallel Giant Slalom', 52);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (38, 'Cycling Men''s 50 kilometres', 20);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (39, 'Rowing Men''s Lightweight Coxless Fours', 44);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (40, 'Athletics Women''s Pole Vault', 6);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (41, 'Biathlon Men''s 12.5 kilometres Pursuit', 12);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (42, 'Cycling Men''s Omnium', 20);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (43, 'Shooting Women''s Air Rifle, 10 metres', 48);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (44, 'Wrestling Men''s Heavyweight, Greco-Roman', 66);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (45, 'Alpine Skiing Women''s Super G', 2);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (46, 'Athletics Men''s 1,500 metres', 6);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (47, 'Taekwondo Men''s Featherweight', 58);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (48, 'Athletics Men''s 2,590 metres Steeplechase', 6);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (49, 'Diving Women''s Synchronized Platform', 21);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (50, 'Jeu De Paume Men''s Singles', 32);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (51, 'Cross Country Skiing Men''s 18 kilometres', 18);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (52, 'Athletics Men''s All-Around Championship', 6);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (53, 'Art Competitions Mixed Painting, Paintings', 5);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (54, 'Swimming Men''s 440 yard Freestyle', 55);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (55, 'Biathlon Men''s 20 kilometres', 12);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (56, 'Weightlifting Women''s Lightweight', 65);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (57, 'Snowboarding Men''s Boardercross', 52);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (58, 'Croquet Mixed Singles, Two Balls', 17);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (59, 'Shooting Men''s Military Rifle, Prone, 300 metres', 48);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (60, 'Cross Country Skiing Men''s 10/15 kilometres Pursuit', 18);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (61, 'Cross Country Skiing Men''s 10 kilometres', 18);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (62, 'Athletics Women''s Marathon', 6);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (63, 'Sailing Mixed 20+ Ton', 47);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (64, 'Cricket Men''s Cricket', 16);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (65, 'Shooting Men''s Rapid-Fire Pistol, 25 metres', 48);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (66, 'Speed Skating Men''s Allround', 54);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (67, 'Weightlifting Men''s Bantamweight', 65);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (68, 'Sailing Mixed 30 metres', 47);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (69, 'Luge Men''s Singles', 35);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (70, 'Swimming Men''s 200 metres Team Swimming', 55);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (71, 'Figure Skating Men''s Special Figures', 24);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (72, 'Canoeing Men''s Canadian Singles, 1,000 metres', 15);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (73, 'Croquet Mixed Singles, One Ball', 17);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (74, 'Canoeing Men''s Canadian Singles, 500 metres', 15);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (75, 'Fencing Women''s Sabre, Individual', 23);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (76, 'Cycling Men''s 100 kilometres Team Time Trial', 20);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (77, 'Athletics Women''s 20 kilometres Walk', 6);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (78, 'Taekwondo Women''s Flyweight', 58);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (79, 'Weightlifting Women''s Featherweight', 65);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (80, 'Athletics Men''s Javelin Throw, Freestyle', 6);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (81, 'Equestrianism Mixed Four-In-Hand Competition', 22);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (82, 'Alpine Skiing Men''s Downhill', 2);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (83, 'Swimming Men''s 100 metres Butterfly', 55);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (84, 'Fencing Men''s epee, Masters, Individual', 23);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (85, 'Shooting Women''s Trap', 48);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (86, 'Archery Men''s Target Archery, 33 metres, Team', 4);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (87, 'Shooting Men''s Air Pistol, 10 metres', 48);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (88, 'Rowing Women''s Coxless Fours', 44);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (89, 'Cycling Men''s 5,000 metres', 20);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (90, 'Shooting Men''s Military Rifle, Kneeling Or Standing, 300 metres', 48);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (91, 'Swimming Men''s Underwater Swimming', 55);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (92, 'Speed Skating Women''s 1,000 metres', 54);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (93, 'Equestrianism Mixed Dressage, Individual', 22);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (94, 'Fencing Men''s Foil, Masters, Individual', 23);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (95, 'Fencing Men''s Foil, Individual', 23);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (96, 'Athletics Women''s 3,000 metres', 6);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (97, 'Short Track Speed Skating Men''s 500 metres', 49);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (98, 'Badminton Women''s Doubles', 7);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (99, 'Shooting Men''s Small-Bore Rifle, Three Positions, 50 metres', 48);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (100, 'Judo Men''s Half-Heavyweight', 33);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (101, 'Freestyle Skiing Men''s Slopestyle', 26);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (102, 'Snowboarding Men''s Halfpipe', 52);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (103, 'Short Track Speed Skating Women''s 1,000 metres', 49);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (104, 'Diving Men''s Springboard', 21);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (105, 'Shooting Men''s Running Target, Single Shot', 48);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (106, 'Shooting Men''s Dueling Pistol, 30 metres', 48);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (107, 'Art Competitions Mixed Painting, Unknown Event', 5);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (108, 'Swimming Men''s 100 metres Freestyle', 55);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (109, 'Shooting Men''s Military Rifle, Any Position, 600 metres', 48);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (110, 'Shooting Men''s Running Target, Single And Double Shot', 48);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (111, 'Alpine Skiing Men''s Giant Slalom', 2);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (112, 'Boxing Men''s Heavyweight', 14);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (113, 'Wrestling Men''s Super-Heavyweight, Freestyle', 66);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (114, 'Cross Country Skiing Women''s 20 kilometres', 18);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (115, 'Sailing Mixed Two Person Heavyweight Dinghy', 47);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (116, 'Bobsleigh Men''s Four', 13);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (117, 'Cycling Men''s 1/4 mile', 20);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (118, 'Wrestling Women''s Flyweight, Freestyle', 66);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (119, 'Sailing Men''s Two Person Keelboat', 47);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (120, 'Short Track Speed Skating Men''s 1,500 metres', 49);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (121, 'Archery Men''s Au Cordon Dore, 50 metres', 4);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (122, 'Equestrianism Men''s Jumping, Team', 22);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (123, 'Boxing Men''s Light-Heavyweight', 14);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (124, 'Shooting Men''s Small-Bore Rifle, Disappearing Target, 25 metres, Team', 48);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (125, 'Shooting Women''s Small-Bore Rifle, Three Positions, 50 metres', 48);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (126, 'Water Polo Men''s Water Polo', 64);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (127, 'Fencing Men''s Single Sticks, Individual', 23);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (128, 'Shooting Men''s Small-Bore Rifle, Prone, 50 metres, Team', 48);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (129, 'Figure Skating Mixed Team', 24);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (130, 'Canoeing Men''s Folding Kayak Doubles, 10 kilometres', 15);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (131, 'Shooting Men''s Small-Bore Rifle, Standing, 50 metres', 48);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (132, 'Snowboarding Women''s Slopestyle', 52);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (133, 'Judo Women''s Middleweight', 33);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (134, 'Volleyball Men''s Volleyball', 63);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (135, 'Athletics Men''s Javelin Throw', 6);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (136, 'Military Ski Patrol Men''s Military Ski Patrol', 36);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (137, 'Cycling Men''s Points Race', 20);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (138, 'Swimming Women''s 10 kilometres Open Water', 55);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (139, 'Cycling Women''s BMX', 20);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (140, 'Cross Country Skiing Women''s 15 kilometres', 18);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (141, 'Art Competitions Mixed Sculpturing, Unknown Event', 5);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (142, 'Taekwondo Men''s Heavyweight', 58);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (143, 'Wrestling Men''s Flyweight, Greco-Roman', 66);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (144, 'Canoeing Men''s Kayak Doubles, 200 metres', 15);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (145, 'Art Competitions Mixed Music, Unknown Event', 5);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (146, 'Baseball Men''s Baseball', 8);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (147, 'Swimming Women''s 100 metres Freestyle', 55);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (148, 'Athletics Men''s Pentathlon (Ancient)', 6);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (149, 'Wrestling Men''s Light-Heavyweight, Freestyle', 66);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (150, 'Shooting Men''s Small-Bore Rifle, 50 and 100 yards, Team', 48);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (151, 'Cycling Women''s Individual Pursuit, 3,000 metres', 20);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (152, 'Luge Mixed Team Relay', 35);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (153, 'Canoeing Men''s Kayak Singles, 500 metres', 15);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (154, 'Triathlon Men''s Olympic Distance', 61);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (155, 'Biathlon Men''s 10 kilometres Sprint', 12);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (156, 'Shooting Men''s Running Target, Single Shot, Team', 48);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (157, 'Cross Country Skiing Men''s 10/10 kilometres Pursuit', 18);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (158, 'Rowing Women''s Coxed Eights', 44);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (159, 'Ski Jumping Men''s Large Hill, Individual', 51);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (160, 'Speed Skating Men''s Team Pursuit (8 laps)', 54);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (161, 'Speed Skating Women''s 5,000 metres', 54);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (162, 'Cycling Men''s 1/3 mile', 20);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (163, 'Modern Pentathlon Men''s Individual', 37);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (164, 'Wrestling Men''s Light-Flyweight, Freestyle', 66);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (165, 'Swimming Men''s 100 Yard Backstroke', 55);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (166, 'Cycling Men''s BMX', 20);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (167, 'Shooting Mixed Free Rifle, Three Positions, 300 metres', 48);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (168, 'Tennis Women''s Doubles', 59);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (169, 'Boxing Men''s Middleweight', 14);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (170, 'Sailing Mixed 3-10 Ton', 47);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (171, 'Cycling Men''s 20 kilometres', 20);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (172, 'Archery Men''s Team Round', 4);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (173, 'Swimming Women''s 4 x 100 metres Freestyle Relay', 55);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (174, 'Gymnastics Men''s Individual All-Around, 5 Events', 28);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (175, 'Fencing Men''s epee, Team', 23);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (176, 'Fencing Men''s Sabre, Team', 23);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (177, 'Gymnastics Men''s Parallel Bars, Teams', 28);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (178, 'Shooting Men''s Dueling Pistol Au Commandement, 25 metres', 48);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (179, 'Gymnastics Men''s Side Horse', 28);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (180, 'Canoeing Men''s Canadian Doubles, 10,000 metres', 15);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (181, 'Bobsleigh Women''s Two', 13);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (182, 'Wrestling Women''s Heavyweight, Freestyle', 66);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (183, 'Diving Men''s Platform', 21);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (184, 'Equestrianism Men''s Three-Day Event, Team', 22);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (185, 'Cycling Men''s Road Race, Individual', 20);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (186, 'Athletics Men''s 3 mile, Team', 6);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (187, 'Cycling Men''s Madison', 20);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (188, 'Swimming Men''s 100 metres Breaststroke', 55);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (189, 'Equestrianism Mixed Long Jump', 22);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (190, 'Weightlifting Men''s Light-Heavyweight', 65);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (191, 'Volleyball Women''s Volleyball', 63);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (192, 'Swimming Men''s 50 metres Freestyle', 55);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (193, 'Sailing Men''s One Person Dinghy', 47);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (194, 'Shooting Men''s Free Pistol, 50 yards, Team', 48);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (195, 'Cycling Women''s Team Pursuit', 20);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (196, 'Shooting Men''s Small Bore-Rifle, Standing, 50 metres, Team', 48);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (197, 'Shooting Men''s Free Rifle, Prone, 300 metres', 48);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (198, 'Biathlon Women''s 3 x 7.5 kilometres Relay', 12);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (199, 'Canoeing Men''s Canadian Singles, 10,000 metres', 15);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (200, 'Cycling Women''s Points Race', 20);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (201, 'Shooting Men''s Running Target, 10 metres', 48);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (202, 'Polo Men''s Polo', 40);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (203, 'Athletics Men''s 110 metres Hurdles', 6);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (204, 'Cross Country Skiing Men''s Sprint', 18);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (205, 'Shooting Men''s Muzzle-Loading Pistol, 25 metres', 48);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (206, 'Athletics Men''s 50 kilometres Walk', 6);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (207, 'Athletics Men''s 4 mile, Team', 6);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (208, 'Athletics Men''s Javelin Throw, Both Hands', 6);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (209, 'Fencing Men''s Sabre, Individual', 23);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (210, 'Rowing Women''s Coxed Fours', 44);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (211, 'Tennis Men''s Doubles', 59);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (212, 'Shooting Men''s Free Pistol, 50 yards', 48);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (213, 'Athletics Women''s 800 metres', 6);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (214, 'Archery Men''s Pole Archery, Small Birds, Team', 4);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (215, 'Athletics Men''s Decathlon', 6);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (216, 'Judo Women''s Half-Lightweight', 33);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (217, 'Figure Skating Mixed Pairs', 24);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (218, 'Athletics Women''s Hammer Throw', 6);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (219, 'Equestrianism Men''s Dressage, Team', 22);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (220, 'Racquets Men''s Singles', 41);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (221, 'Gymnastics Men''s Rope Climbing', 28);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (222, 'Athletics Women''s 3,000 metres Steeplechase', 6);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (223, 'Cycling Women''s Mountainbike, Cross-Country', 20);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (224, 'Gymnastics Women''s Uneven Bars', 28);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (225, 'Lacrosse Men''s Lacrosse', 34);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (226, 'Archery Men''s Double American Round', 4);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (227, 'Sailing Men''s Skiff', 47);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (228, 'Swimming Men''s 100 metres Freestyle For Sailors', 55);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (229, 'Athletics Men''s 1,600 metres Medley Relay', 6);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (230, 'Table Tennis Men''s Singles', 57);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (231, 'Boxing Men''s Light-Welterweight', 14);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (232, 'Cycling Women''s Individual Time Trial', 20);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (233, 'Canoeing Women''s Kayak Singles, 500 metres', 15);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (234, 'Tennis Women''s Singles, Covered Courts', 59);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (235, 'Freestyle Skiing Women''s Aerials', 26);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (236, 'Sailing Women''s One Person Dinghy', 47);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (237, 'Freestyle Skiing Women''s Moguls', 26);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (238, 'Nordic Combined Men''s Normal Hill / 10 km, Individual', 39);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (239, 'Rowing Women''s Coxed Quadruple Sculls', 44);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (240, 'Snowboarding Men''s Parallel Giant Slalom', 52);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (241, 'Athletics Men''s Shot Put, Both Hands', 6);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (242, 'Athletics Women''s 5,000 metres', 6);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (243, 'Boxing Women''s Middleweight', 14);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (244, 'Diving Women''s Platform', 21);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (245, 'Shooting Men''s Free Pistol, 25 metres', 48);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (246, 'Swimming Men''s 400 metres Freestyle', 55);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (247, 'Swimming Women''s 400 metres Freestyle', 55);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (248, 'Curling Women''s Curling', 19);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (249, 'Speed Skating Men''s 5,000 metres', 54);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (250, 'Swimming Women''s 100 metres Breaststroke', 55);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (251, 'Swimming Women''s 800 metres Freestyle', 55);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (252, 'Nordic Combined Men''s Team', 39);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (253, 'Athletics Men''s 400 metres Hurdles', 6);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (254, 'Shooting Men''s Military Rifle, 200/500/600/800/900/1,000 Yards, Team', 48);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (255, 'Swimming Women''s 200 metres Breaststroke', 55);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (256, 'Snowboarding Men''s Giant Slalom', 52);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (257, 'Rowing Men''s Coxed Fours, Inriggers', 44);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (258, 'Swimming Men''s 200 metres Obstacle Course', 55);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (259, 'Synchronized Swimming Women''s Duet', 56);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (260, 'Swimming Women''s 100 metres Butterfly', 55);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (261, 'Athletics Men''s 400 metres', 6);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (262, 'Nordic Combined Men''s Sprint', 39);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (263, 'Athletics Women''s Pentathlon', 6);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (264, 'Canoeing Women''s Kayak Singles, 200 metres', 15);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (265, 'Speed Skating Women''s 500 metres', 54);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (266, 'Cycling Men''s Sprint', 20);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (267, 'Art Competitions Mixed Literature, Unknown Event', 5);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (268, 'Cross Country Skiing Women''s 5/5 kilometres Pursuit', 18);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (269, 'Diving Men''s Synchronized Platform', 21);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (270, 'Sailing Mixed Open', 47);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (271, 'Alpinism Mixed Alpinism', 3);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (272, 'Art Competitions Mixed Literature, Dramatic Works', 5);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (273, 'Bobsleigh Men''s Four/Five', 13);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (274, 'Athletics Men''s 10 mile Walk', 6);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (275, 'Athletics Men''s Shot Put', 6);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (276, 'Sailing Mixed 1-2 Ton', 47);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (277, 'Cycling Men''s 25 mile', 20);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (278, 'Athletics Men''s Pole Vault', 6);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (279, 'Weightlifting Women''s Super-Heavyweight', 65);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (280, 'Weightlifting Men''s Lightweight', 65);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (281, 'Archery Women''s Individual', 4);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (282, 'Swimming Men''s 4 x 100 metres Freestyle Relay', 55);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (283, 'Athletics Women''s 4 x 400 metres Relay', 6);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (284, 'Diving Women''s Plain High', 21);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (285, 'Alpine Skiing Women''s Downhill', 2);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (286, 'Athletics Women''s 100 metres Hurdles', 6);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (287, 'Sailing Men''s Two Person Dinghy', 47);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (288, 'Alpine Skiing Women''s Slalom', 2);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (289, 'Table Tennis Women''s Doubles', 57);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (290, 'Alpine Skiing Men''s Slalom', 2);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (291, 'Archery Men''s Au Chapelet, 50 metres', 4);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (292, 'Tennis Women''s Singles', 59);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (293, 'Shooting Women''s Skeet', 48);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (294, 'Art Competitions Mixed Literature', 5);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (295, 'Cross Country Skiing Women''s 5/10 kilometres Pursuit', 18);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (296, 'Sailing Women''s Two Person Dinghy', 47);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (297, 'Shooting Men''s Small-Bore Rifle, Disappearing Target, 25 metres', 48);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (298, 'Rowing Men''s Coxed Eights', 44);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (299, 'Gymnastics Men''s Pommelled Horse', 28);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (300, 'Judo Men''s Open Class', 33);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (301, 'Athletics Men''s 1,500 metres Walk', 6);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (302, 'Sailing Mixed Windsurfer', 47);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (303, 'Wrestling Men''s Light-Flyweight, Greco-Roman', 66);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (304, 'Ski Jumping Men''s Normal Hill, Individual', 51);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (305, 'Art Competitions Mixed Sculpturing, Reliefs', 5);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (306, 'Sailing Mixed Multihull', 47);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (307, 'Cycling Women''s Road Race, Individual', 20);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (308, 'Racquets Men''s Doubles', 41);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (309, 'Sailing Mixed 6.5 metres', 47);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (310, 'Biathlon Men''s 15 kilometres Mass Start', 12);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (311, 'Short Track Speed Skating Men''s 1,000 metres', 49);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (312, 'Taekwondo Women''s Featherweight', 58);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (313, 'Sailing Women''s Windsurfer', 47);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (314, 'Shooting Men''s Free Rifle, Standing, 300 metres', 48);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (315, 'Sailing Mixed 6 metres', 47);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (316, 'Archery Women''s Double Columbia Round', 4);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (317, 'Swimming Men''s 4,000 metres Freestyle', 55);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (318, 'Rowing Men''s Double Sculls', 44);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (319, 'Speed Skating Men''s 1,500 metres', 54);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (320, 'Sailing Mixed 0.5-1 Ton', 47);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (321, 'Wrestling Men''s Bantamweight, Greco-Roman', 66);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (322, 'Canoeing Men''s Canadian Doubles, Slalom', 15);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (323, 'Boxing Men''s Flyweight', 14);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (324, 'Art Competitions Mixed Music, Vocals', 5);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (325, 'Wrestling Men''s Heavyweight, Freestyle', 66);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (326, 'Cross Country Skiing Women''s Sprint', 18);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (327, 'Croquet Mixed Doubles', 17);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (328, 'Art Competitions Mixed Sculpturing, Statues', 5);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (329, 'Hockey Men''s Hockey', 30);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (330, 'Weightlifting Men''s Flyweight', 65);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (331, 'Snowboarding Women''s Giant Slalom', 52);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (332, 'Biathlon Women''s 15 kilometres', 12);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (333, 'Equestrianism Men''s Three-Day Event, Individual', 22);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (334, 'Shooting Mixed Small-Bore Rifle, Three Positions, 50 metres', 48);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (335, 'Biathlon Women''s 4 x 7.5 kilometres Relay', 12);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (336, 'Gymnastics Women''s Horse Vault', 28);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (337, 'Rugby Sevens Men''s Rugby Sevens', 46);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (338, 'Swimming Women''s 100 metres Backstroke', 55);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (339, 'Gymnastics Men''s Individual All-Around, 4 Events', 28);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (340, 'Badminton Women''s Singles', 7);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (341, 'Archery Men''s Pole Archery, Large Birds, Individual', 4);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (342, 'Shooting Men''s Dueling Pistol, 30 metres, Team', 48);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (343, 'Rowing Men''s Coxless Fours', 44);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (344, 'Canoeing Men''s Kayak Doubles, 1,000 metres', 15);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (345, 'Cycling Men''s 100 kilometres', 20);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (346, 'Judo Men''s Heavyweight', 33);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (347, 'Cycling Men''s Individual Time Trial', 20);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (348, 'Ice Hockey Women''s Ice Hockey', 31);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (349, 'Athletics Women''s Triple Jump', 6);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (350, 'Wrestling Men''s Unlimited Class, Greco-Roman', 66);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (351, 'Cycling Women''s 500 metres Time Trial', 20);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (352, 'Archery Men''s Double York Round', 4);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (353, 'Judo Men''s Half-Middleweight', 33);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (354, 'Equestrianism Mixed Hacks And Hunter Combined', 22);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (355, 'Biathlon Women''s 4 x 6 kilometres Relay', 12);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (356, 'Cross Country Skiing Women''s 30 kilometres', 18);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (357, 'Weightlifting Men''s Super-Heavyweight', 65);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (358, 'Weightlifting Men''s Middle-Heavyweight', 65);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (359, 'Cycling Men''s 1/2 mile', 20);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (360, 'Rowing Women''s Lightweight Double Sculls', 44);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (361, 'Gymnastics Women''s Individual All-Around', 28);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (362, 'Freestyle Skiing Women''s Slopestyle', 26);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (363, 'Shooting Men''s Free Rifle, 400, 600 and 800 metres, Team', 48);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (364, 'Shooting Men''s Military Rifle, Prone, 600 metres, Team', 48);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (365, 'Diving Women''s Synchronized Springboard', 21);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (366, 'Equestrianism Mixed Dressage, Team', 22);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (367, 'Rowing Men''s Lightweight Double Sculls', 44);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (368, 'Athletics Men''s 2,500 metres Steeplechase', 6);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (369, 'Swimming Men''s 200 metres Breaststroke', 55);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (370, 'Wrestling Men''s Middleweight A, Greco-Roman', 66);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (371, 'Judo Women''s Half-Middleweight', 33);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (372, 'Boxing Women''s Flyweight', 14);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (373, 'Swimming Men''s 4 x 100 metres Medley Relay', 55);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (374, 'Water Polo Women''s Water Polo', 64);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (375, 'Art Competitions Mixed Painting, Drawings And Water Colors', 5);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (376, 'Shooting Men''s Small-Bore Rifle, Moving Target, 25 yards', 48);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (377, 'Cross Country Skiing Women''s 3 x 5 kilometres Relay', 18);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (378, 'Shooting Mixed Free Pistol, 50 metres', 48);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (379, 'Modern Pentathlon Men''s Team', 37);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (380, 'Swimming Men''s Plunge For Distance', 55);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (381, 'Sailing Mixed 12 metres', 47);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (382, 'Boxing Men''s Light-Middleweight', 14);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (383, 'Fencing Men''s Sabre, Masters, Individual', 23);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (384, 'Beach Volleyball Men''s Beach Volleyball', 11);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (385, 'Athletics Men''s Marathon', 6);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (386, 'Shooting Men''s Military Pistol, Team', 48);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (387, 'Cycling Men''s 1 mile', 20);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (388, 'Swimming Men''s 220 yard Freestyle', 55);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (389, 'Athletics Men''s Standing Long Jump', 6);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (390, 'Shooting Mixed Skeet', 48);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (391, 'Tennis Mixed Doubles, Covered Courts', 59);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (392, 'Fencing Women''s epee, Team', 23);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (393, 'Snowboarding Men''s Slopestyle', 52);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (394, 'Shooting Men''s Trap, Team', 48);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (395, 'Skeleton Men''s Skeleton', 50);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (396, 'Rhythmic Gymnastics Women''s Individual', 42);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (397, 'Badminton Men''s Doubles', 7);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (398, 'Football Men''s Football', 25);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (399, 'Gymnastics Men''s Horizontal Bar, Teams', 28);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (400, 'Shooting Men''s Trap', 48);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (401, 'Swimming Women''s 4 x 200 metres Freestyle Relay', 55);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (402, 'Canoeing Men''s Kayak Relay 4 x 500 metres', 15);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (403, 'Weightlifting Men''s Featherweight', 65);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (404, 'Cycling Women''s Omnium', 20);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (405, 'Canoeing Men''s Kayak Singles, 10,000 metres', 15);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (406, 'Shooting Men''s Military Rifle, 200, 400, 500 and 600 metres, Team', 48);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (407, 'Wrestling Men''s Bantamweight, Freestyle', 66);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (408, 'Art Competitions Mixed Painting, Applied Arts', 5);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (409, 'Swimming Women''s 200 metres Butterfly', 55);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (410, 'Athletics Men''s 5 mile', 6);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (411, 'Basketball Men''s Basketball', 9);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (412, 'Equestrianism Mixed Jumping, Individual', 22);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (413, 'Equestrianism Mixed High Jump', 22);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (414, 'Equestrianism Mixed Three-Day Event, Team', 22);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (415, 'Ski Jumping Women''s Normal Hill, Individual', 51);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (416, 'Shooting Men''s Military Revolver, 1873-1874 Gras Model, 20 metres', 48);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (417, 'Shooting Men''s Military Rifle, 200 metres', 48);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (418, 'Trampolining Women''s Individual', 60);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (419, 'Judo Women''s Lightweight', 33);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (420, 'Archery Men''s Pole Archery, Small Birds, Individual', 4);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (421, 'Snowboarding Women''s Halfpipe', 52);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (422, 'Shooting Women''s Air Pistol, 10 metres', 48);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (423, 'Archery Men''s Individual', 4);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (424, 'Art Competitions Mixed Literature, Lyric Works', 5);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (425, 'Canoeing Men''s Canadian Doubles, 1,000 metres', 15);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (426, 'Canoeing Men''s Kayak Doubles, 10,000 metres', 15);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (427, 'Swimming Women''s 200 metres Backstroke', 55);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (428, 'Judo Men''s Extra-Lightweight', 33);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (429, 'Table Tennis Men''s Doubles', 57);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (430, 'Swimming Men''s 100 yard Freestyle', 55);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (431, 'Athletics Men''s Long Jump', 6);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (432, 'Swimming Men''s 10 kilometres Open Water', 55);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (433, 'Cycling Men''s Keirin', 20);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (434, 'Athletics Men''s 10,000 metres', 6);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (435, 'Canoeing Women''s Kayak Fours, 500 metres', 15);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (436, 'Shooting Men''s Military Revolver, 20 metres', 48);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (437, 'Trampolining Men''s Individual', 60);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (438, 'Triathlon Women''s Olympic Distance', 61);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (439, 'Shooting Men''s Small-Bore Rifle, Prone, 50 metres', 48);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (440, 'Sailing Mixed 8 metres', 47);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (441, 'Swimming Men''s 400 metres Individual Medley', 55);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (442, 'Cycling Men''s Tandem Sprint, 2,000 metres', 20);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (443, 'Gymnastics Men''s Individual All-Around, Field Sports', 28);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (444, 'Shooting Men''s Free Pistol, 30 metres', 48);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (445, 'Shooting Men''s Military Rifle, 1873-1874 Gras Model, Kneeling Or Standing, 200 metres', 48);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (446, 'Art Competitions Mixed Sculpturing, Medals', 5);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (447, 'Shooting Men''s Small-Bore Rifle, Prone, 50 and 100 yards', 48);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (448, 'Athletics Women''s High Jump', 6);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (449, 'Archery Men''s Continental Style', 4);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (450, 'Canoeing Men''s Kayak Singles, Slalom', 15);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (451, 'Speed Skating Men''s 1,000 metres', 54);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (452, 'Archery Men''s Target Archery, 50 metres, Team', 4);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (453, 'Athletics Women''s 4 x 100 metres Relay', 6);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (454, 'Athletics Men''s Hammer Throw', 6);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (455, 'Art Competitions Mixed Sculpturing', 5);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (456, 'Synchronized Swimming Women''s Team', 56);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (457, 'Archery Women''s Team', 4);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (458, 'Weightlifting Women''s Light-Heavyweight', 65);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (459, 'Softball Women''s Softball', 53);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (460, 'Athletics Men''s 4 x 400 metres Relay', 6);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (461, 'Wrestling Men''s Middleweight B, Greco-Roman', 66);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (462, 'Fencing Women''s Foil, Team', 23);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (463, 'Cycling Men''s Team Sprint', 20);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (464, 'Shooting Men''s Military Rifle, Standing, 300 metres', 48);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (465, 'Athletics Men''s 3,000 metres, Team', 6);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (466, 'Curling Men''s Curling', 19);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (467, 'Shooting Men''s Free Rifle, 1,000 Yards', 48);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (468, 'Art Competitions Mixed Architecture, Designs For Town Planning', 5);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (469, 'Swimming Men''s 4 x 250 metres Freestyle Relay', 55);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (470, 'Athletics Women''s 100 metres', 6);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (471, 'Tennis Men''s Doubles, Covered Courts', 59);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (472, 'Shooting Men''s Military Rifle, 300 metres and 600 metres, Prone, Team', 48);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (473, 'Cycling Men''s Mountainbike, Cross-Country', 20);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (474, 'Speed Skating Men''s 500 metres', 54);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (475, 'Gymnastics Men''s Horizontal Bar', 28);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (476, 'Athletics Men''s High Jump', 6);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (477, 'Sailing Women''s Skiff', 47);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (478, 'Taekwondo Women''s Heavyweight', 58);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (479, 'Archery Men''s Target Archery, 28 metres, Individual', 4);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (480, 'Rowing Men''s Coxed Pairs (1 mile)', 44);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (481, 'Motorboating Mixed B-Class (Under 60 Feet)', 38);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (482, 'Wrestling Men''s Lightweight, Freestyle', 66);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (483, 'Beach Volleyball Women''s Beach Volleyball', 11);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (484, 'Gymnastics Men''s Team All-Around', 28);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (485, 'Swimming Men''s 400 metres Breaststroke', 55);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (486, 'Gymnastics Men''s Parallel Bars', 28);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (487, 'Speed Skating Women''s 3,000 metres', 54);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (488, 'Shooting Men''s Running Target, Double Shot', 48);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (489, 'Judo Men''s Half-Lightweight', 33);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (490, 'Cross Country Skiing Men''s 30 kilometres', 18);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (491, 'Equestrianism Men''s Dressage, Individual', 22);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (492, 'Swimming Women''s 400 metres Individual Medley', 55);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (493, 'Archery Men''s Target Archery, 50 metres, Individual', 4);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (494, 'Athletics Women''s 1,500 metres', 6);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (495, 'Skeleton Women''s Skeleton', 50);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (496, 'Wrestling Men''s Light-Heavyweight, Greco-Roman', 66);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (497, 'Luge Mixed (Men)''s Doubles', 35);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (498, 'Shooting Men''s Free Rifle, Kneeling, 300 metres', 48);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (499, 'Athletics Women''s Long Jump', 6);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (500, 'Archery Women''s Double National Round', 4);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (501, 'Sailing Men''s One Person Heavyweight Dinghy', 47);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (502, 'Art Competitions Mixed Sculpturing, Medals And Reliefs', 5);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (503, 'Cross Country Skiing Women''s 5 kilometres', 18);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (504, 'Art Competitions Mixed Painting, Graphic Arts', 5);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (505, 'Short Track Speed Skating Men''s 5,000 metres Relay', 49);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (506, 'Figure Skating Women''s Singles', 24);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (507, 'Rowing Men''s Coxed Pairs', 44);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (508, 'Diving Men''s Synchronized Springboard', 21);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (509, 'Alpine Skiing Women''s Combined', 2);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (510, 'Gymnastics Men''s Rings', 28);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (511, 'Sailing Mixed 5.5 metres', 47);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (512, 'Basque Pelota Men''s Two-Man Teams With Cesta', 10);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (513, 'Canoeing Men''s Folding Kayak Singles, 10 kilometres', 15);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (514, 'Snowboarding Women''s Parallel Slalom', 52);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (515, 'Shooting Mixed Small-Bore Rifle, Prone, 50 metres', 48);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (516, 'Sailing Mixed Two Person Keelboat', 47);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (517, 'Tennis Mixed Doubles', 59);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (518, 'Speed Skating Women''s 1,500 metres', 54);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (519, 'Cycling Men''s Team Pursuit, 1,980 yards', 20);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (520, 'Swimming Men''s 500 metres Freestyle', 55);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (521, 'Cross Country Skiing Men''s 30 km Skiathlon', 18);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (522, 'Rhythmic Gymnastics Women''s Group', 42);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (523, 'Cycling Men''s 5 mile', 20);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (524, 'Athletics Men''s Cross-Country, Individual', 6);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (525, 'Shooting Men''s Free Pistol, 50 metres', 48);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (526, 'Alpine Skiing Men''s Combined', 2);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (527, 'Wrestling Women''s Light-Heavyweight, Freestyle', 66);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (528, 'Swimming Men''s 200 metres Backstroke', 55);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (529, 'Art Competitions Mixed Music, Compositions For Orchestra', 5);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (530, 'Shooting Men''s Military Pistol, 30 metres', 48);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (531, 'Freestyle Skiing Women''s Halfpipe', 26);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (532, 'Art Competitions Mixed Architecture, Unknown Event', 5);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (533, 'Weightlifting Men''s Heavyweight I', 65);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (534, 'Swimming Men''s 440 Yard Breaststroke', 55);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (535, 'Athletics Men''s 3,500 metres Walk', 6);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (536, 'Athletics Men''s 800 metres', 6);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (537, 'Athletics Women''s 200 metres', 6);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (538, 'Wrestling Men''s Middleweight, Greco-Roman', 66);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (539, 'Swimming Men''s 200 metres Individual Medley', 55);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (540, 'Biathlon Women''s 12.5 kilometres Mass Start', 12);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (541, 'Freestyle Skiing Men''s Halfpipe', 26);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (542, 'Canoeing Women''s Kayak Singles, Slalom', 15);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (543, 'Gymnastics Men''s Club Swinging', 28);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (544, 'Wrestling Women''s Middleweight, Freestyle', 66);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (545, 'Rowing Men''s Coxed Fours', 44);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (546, 'Archery Men''s Target Archery, 28 metres, Team', 4);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (547, 'Snowboarding Women''s Boardercross', 52);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (548, 'Swimming Men''s 200 metres Freestyle', 55);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (549, 'Gymnastics Women''s Balance Beam', 28);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (550, 'Swimming Men''s 4 x 50 Yard Freestyle Relay', 55);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (551, 'Sailing Mixed 7 metres', 47);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (552, 'Synchronized Swimming Women''s Solo', 56);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (553, 'Weightlifting Women''s Heavyweight', 65);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (554, 'Archery Men''s Sur La Perche a La Herse', 4);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (555, 'Equestrianism Men''s Jumping, Individual', 22);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (556, 'Cycling Men''s 1,000 metres Time Trial', 20);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (557, 'Shooting Men''s Skeet', 48);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (558, 'Athletics Men''s 3,000 metres Steeplechase', 6);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (559, 'Rowing Women''s Single Sculls', 44);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (560, 'Cross Country Skiing Women''s Team Sprint', 18);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (561, 'Swimming Men''s 50 yard Freestyle', 55);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (562, 'Shooting Men''s Military Rifle, Standing, 300 metres, Team', 48);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (563, 'Figure Skating Men''s Singles', 24);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (564, 'Archery Men''s Au Cordon Dore, 33 metres', 4);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (565, 'Gymnastics Women''s Floor Exercise', 28);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (566, 'Biathlon Mixed 2 x 6 kilometres and 2 x 7.5 kilometres Relay', 12);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (567, 'Art Competitions Mixed Painting', 5);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (568, 'Freestyle Skiing Men''s Moguls', 26);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (569, 'Shooting Mixed Running Target, 50 metres', 48);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (570, 'Shooting Men''s Military Rifle, Three Positions, 300 metres', 48);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (571, 'Rowing Men''s Quadruple Sculls', 44);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (572, 'Canoeing Men''s Canadian Doubles, 500 metres', 15);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (573, 'Art Competitions Mixed Architecture', 5);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (574, 'Swimming Men''s 100 metres Backstroke', 55);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (575, 'Cycling Men''s 25 kilometres', 20);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (576, 'Roque Men''s Singles', 43);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (577, 'Cross Country Skiing Men''s Team Sprint', 18);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (578, 'Canoeing Women''s Kayak Doubles, 500 metres', 15);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (579, 'Ski Jumping Men''s Large Hill, Team', 51);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (580, 'Bobsleigh Men''s Two', 13);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (581, 'Speed Skating Women''s Team Pursuit (6 laps)', 54);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (582, 'Cycling Men''s Individual Pursuit, 4,000 metres', 20);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (583, 'Shooting Men''s Free Pistol, 50 metres, Team', 48);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (584, 'Rugby Sevens Women''s Rugby Sevens', 46);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (585, 'Taekwondo Men''s Welterweight', 58);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (586, 'Athletics Women''s 80 metres Hurdles', 6);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (587, 'Gymnastics Women''s Team Portable Apparatus', 28);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (588, 'Sailing Mixed 10-20 Ton', 47);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (589, 'Athletics Men''s 5,000 metres', 6);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (590, 'Boxing Women''s Lightweight', 14);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (591, 'Swimming Men''s One Mile Freestyle', 55);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (592, 'Cycling Men''s 333 metres Time Trial', 20);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (593, 'Art Competitions Mixed Unknown Event', 5);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (594, 'Athletics Women''s 10,000 metres', 6);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (595, 'Canoeing Men''s Kayak Doubles, 500 metres', 15);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (596, 'Weightlifting Men''s Unlimited, One Hand', 65);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (597, 'Wrestling Men''s Lightweight, Greco-Roman', 66);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (598, 'Weightlifting Men''s All-Around Dumbbell Contest', 65);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (599, 'Taekwondo Women''s Welterweight', 58);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (600, 'Figure Skating Mixed Ice Dancing', 24);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (601, 'Athletics Men''s Pentathlon', 6);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (602, 'Athletics Men''s 3,200 metres Steeplechase', 6);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (603, 'Canoeing Men''s Canadian Singles, 200 metres', 15);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (604, 'Freestyle Skiing Women''s Ski Cross', 26);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (605, 'Gymnastics Men''s Individual All-Around', 28);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (606, 'Athletics Men''s 3,000 metres Walk', 6);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (607, 'Sailing Mixed Three Person Keelboat', 47);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (608, 'Fencing Women''s Sabre, Team', 23);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (609, 'Archery Men''s Team', 4);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (610, 'Art Competitions Mixed Music, Instrumental And Chamber', 5);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (611, 'Hockey Women''s Hockey', 30);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (612, 'Swimming Women''s 4 x 100 metres Medley Relay', 55);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (613, 'Swimming Women''s 50 metres Freestyle', 55);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (614, 'Taekwondo Men''s Flyweight', 58);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (615, 'Alpine Skiing Women''s Giant Slalom', 2);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (616, 'Rowing Men''s Coxless Pairs', 44);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (617, 'Fencing Men''s Foil, Team', 23);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (618, 'Handball Women''s Handball', 29);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (619, 'Weightlifting Men''s Heavyweight II', 65);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (620, 'Shooting Men''s Running Target, 50 metres', 48);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (621, 'Rowing Men''s Single Sculls', 44);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (622, 'Athletics Women''s 400 metres Hurdles', 6);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (623, 'Archery Women''s Team Round', 4);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (624, 'Athletics Men''s Discus Throw, Both Hands', 6);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (625, 'Nordic Combined Men''s Individual', 39);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (626, 'Boxing Men''s Super-Heavyweight', 14);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (627, 'Golf Men''s Team', 27);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (628, 'Handball Men''s Handball', 29);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (629, 'Biathlon Women''s 7.5 kilometres Sprint', 12);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (630, 'Cycling Women''s Sprint', 20);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (631, 'Athletics Men''s 200 metres', 6);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (632, 'Wrestling Men''s Featherweight, Freestyle', 66);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (633, 'Table Tennis Women''s Team', 57);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (634, 'Snowboarding Men''s Parallel Slalom', 52);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (635, 'Judo Men''s Lightweight', 33);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (636, 'Swimming Women''s 200 metres Freestyle', 55);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (637, 'Equestrianism Men''s Vaulting, Individual', 22);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (638, 'Rugby Men''s Rugby', 45);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (639, 'Shooting Men''s Military Rifle, Prone, 300 metres, Team', 48);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (640, 'Wrestling Men''s Welterweight, Freestyle', 66);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (641, 'Golf Women''s Individual', 27);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (642, 'Aeronautics Mixed Aeronautics', 1);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (643, 'Shooting Men''s Trap, Single Shot, 16 metres', 48);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (644, 'Sailing Mixed 18 foot', 47);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (645, 'Badminton Mixed Doubles', 7);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (646, 'Swimming Men''s 1,200 metres Freestyle', 55);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (647, 'Athletics Men''s 10 kilometres Walk', 6);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (648, 'Shooting Men''s Small-Bore Rifle, Disappearing Target, 25 yards', 48);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (649, 'Rowing Men''s Coxed Pairs (1 kilometres)', 44);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (650, 'Table Tennis Women''s Singles', 57);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (651, 'Gymnastics Men''s Floor Exercise', 28);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (652, 'Alpine Skiing Men''s Super G', 2);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (653, 'Shooting Men''s Small-Bore Rifle, Any Position, 50 metres', 48);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (654, 'Shooting Men''s Free Rifle, Three Positions, 300 metres', 48);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (655, 'Tennis Men''s Singles, Covered Courts', 59);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (656, 'Rowing Men''s Coxed Fours, Outriggers', 44);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (657, 'Athletics Men''s Stone Throw', 6);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (658, 'Ice Hockey Men''s Ice Hockey', 31);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (659, 'Canoeing Men''s Kayak Singles, 200 metres', 15);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (660, 'Art Competitions Mixed Sculpturing, Medals And Plaques', 5);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (661, 'Freestyle Skiing Men''s Ski Cross', 26);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (662, 'Shooting Men''s Running Target, Double Shot, Team', 48);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (663, 'Swimming Men''s 880 yard Freestyle', 55);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (664, 'Rowing Men''s 6-Man Naval Rowing Boats', 44);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (665, 'Archery Men''s Championnat Du Monde', 4);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (666, 'Wrestling Women''s Lightweight, Freestyle', 66);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (667, 'Shooting Women''s Double Trap', 48);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (668, 'Shooting Men''s Free Rifle, Three Positions, 300 metres, Team', 48);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (669, 'Athletics Women''s Shot Put', 6);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (670, 'Fencing Women''s Foil, Individual', 23);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (671, 'Golf Men''s Individual', 27);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (672, 'Athletics Women''s Javelin Throw', 6);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (673, 'Shooting Men''s Free Rifle, Any Position, 300 metres', 48);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (674, 'Athletics Women''s 400 metres', 6);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (675, 'Wrestling Men''s Middleweight, Freestyle', 66);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (676, 'Wrestling Women''s Featherweight, Freestyle', 66);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (677, 'Shooting Mixed Rapid-Fire Pistol, 25 metres', 48);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (678, 'Equestrianism Mixed Three-Day Event, Individual', 22);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (679, 'Fencing Men''s epee, Individual', 23);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (680, 'Archery Men''s Pole Archery, Large Birds, Team', 4);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (681, 'Tennis Men''s Singles', 59);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (682, 'Tug-Of-War Men''s Tug-Of-War', 62);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (683, 'Athletics Men''s Standing Triple Jump', 6);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (684, 'Cycling Men''s 10,000 metres', 20);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (685, 'Gymnastics Men''s Horse Vault', 28);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (686, 'Sailing Women''s Three Person Keelboat', 47);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (687, 'Shooting Men''s Dueling Pistol Au Vise 20 metres', 48);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (688, 'Archery Men''s Au Chapelet, 33 metres', 4);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (689, 'Sailing Mixed Two Person Dinghy', 47);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (690, 'Shooting Men''s Military Pistol, 25 metres', 48);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (691, 'Shooting Men''s Air Rifle, 10 metres', 48);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (692, 'Biathlon Women''s 10 kilometres Pursuit', 12);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (693, 'Luge Women''s Singles', 35);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (694, 'Art Competitions Mixed Music', 5);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (695, 'Wrestling Men''s Super-Heavyweight, Greco-Roman', 66);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (696, 'Canoeing Men''s Kayak Singles, 1,000 metres', 15);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (697, 'Sailing Mixed 2-3 Ton', 47);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (698, 'Wrestling Men''s Featherweight, Greco-Roman', 66);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (699, 'Athletics Men''s 56-pound Weight Throw', 6);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (700, 'Cross Country Skiing Men''s 50 kilometres', 18);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (701, 'Equestrianism Men''s Vaulting, Team', 22);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (702, 'Shooting Women''s Sporting Pistol, 25 metres', 48);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (703, 'Judo Women''s Half-Heavyweight', 33);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (704, 'Athletics Men''s 100 metres', 6);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (705, 'Biathlon Men''s 4 x 7.5 kilometres Relay', 12);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (706, 'Weightlifting Men''s Unlimited, Two Hands', 65);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (707, 'Athletics Men''s 4 x 100 metres Relay', 6);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (708, 'Cycling Men''s Team Pursuit, 4,000 metres', 20);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (709, 'Diving Women''s Springboard', 21);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (710, 'Sailing Men''s Windsurfer', 47);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (711, 'Swimming Men''s 4 x 200 metres Freestyle Relay', 55);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (712, 'Weightlifting Women''s Flyweight', 65);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (713, 'Cycling Women''s Team Sprint', 20);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (714, 'Athletics Men''s Cross-Country, Team', 6);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (715, 'Athletics Men''s Discus Throw, Greek Style', 6);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (716, 'Archery Men''s Sur La Perche a La Pyramide', 4);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (717, 'Badminton Men''s Singles', 7);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (718, 'Sailing Mixed Skiff', 47);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (719, 'Wrestling Men''s Flyweight, Freestyle', 66);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (720, 'Athletics Men''s 5,000 metres, Team', 6);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (721, 'Judo Women''s Heavyweight', 33);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (722, 'Cross Country Skiing Women''s 4 x 5 kilometres Relay', 18);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (723, 'Gymnastics Men''s Team All-Around, Swedish System', 28);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (724, 'Cycling Men''s 12-Hours Race', 20);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (725, 'Art Competitions Mixed Music, Compositions For Solo Or Chorus', 5);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (726, 'Shooting Men''s Military Rifle, Prone, 600 metres', 48);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (727, 'Shooting Mixed Trap', 48);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (728, 'Gymnastics Men''s Team All-Around, Free System', 28);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (729, 'Swimming Women''s 200 metres Individual Medley', 55);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (730, 'Fencing Men''s Sabre, Individual, Three Hits', 23);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (731, 'Athletics Men''s 60 metres', 6);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (732, 'Shooting Men''s Double Trap', 48);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (733, 'Cross Country Skiing Men''s 15 kilometres', 18);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (734, 'Boxing Men''s Lightweight', 14);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (735, 'Shooting Men''s Free Rifle, Prone, 600 metres', 48);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (736, 'Table Tennis Men''s Team', 57);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (737, 'Canoeing Men''s Kayak Fours, 1,000 metres', 15);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (738, 'Rowing Women''s Double Sculls', 44);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (739, 'Canoeing Men''s Canadian Singles, Slalom', 15);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (740, 'Sailing Mixed 10 metres', 47);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (741, 'Basketball Women''s Basketball', 9);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (742, 'Fencing Women''s epee, Individual', 23);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (743, 'Equestrianism Mixed Jumping, Team', 22);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (744, 'Motorboating Mixed A-Class (Open)', 38);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (745, 'Athletics Men''s Discus Throw', 6);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (746, 'Rowing Men''s 17-Man Naval Rowing Boats', 44);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (747, 'Short Track Speed Skating Women''s 3,000 metres Relay', 49);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (748, 'Weightlifting Men''s Heavyweight', 65);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (749, 'Boxing Men''s Light-Flyweight', 14);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (750, 'Short Track Speed Skating Women''s 1,500 metres', 49);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (751, 'Gymnastics Men''s Individual All-Around, Apparatus Work', 28);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (752, 'Athletics Men''s Triple Jump', 6);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (753, 'Sailing Mixed 40 metres', 47);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (754, 'Gymnastics Men''s Tumbling', 28);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (755, 'Sailing Mixed 12 foot', 47);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (756, 'Athletics Women''s Heptathlon', 6);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (757, 'Athletics Men''s 4,000 metres Steeplechase', 6);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (758, 'Short Track Speed Skating Women''s 500 metres', 49);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (759, 'Nordic Combined Men''s Large Hill / 10 km, Individual', 39);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (760, 'Athletics Men''s 200 metres Hurdles', 6);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (761, 'Athletics Men''s Standing High Jump', 6);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (762, 'Boxing Men''s Featherweight', 14);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (763, 'Boxing Men''s Bantamweight', 14);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (764, 'Fencing Men''s epee, Masters and Amateurs, Individual', 23);
INSERT INTO dbo.event (event_code, event_description, sport_code) VALUES (765, 'Rowing Women''s Quadruple Sculls', 44);
